In [3]:
import pandas as pd

#load data
df = pd.read_csv('Dataset/Dataset1.csv')

df

,timestamp,source,log_message,target_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status
...,...,...,...,...
2405,13-08-2025 07:29,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status
2406,01-11-2025 05:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert
2407,03-08-2025 03:07,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status
2408,11-11-2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert

In [4]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [5]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [6]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

# 1. load your data
# csv_path = r"synthetic_logs.csv"
# df = pd.read_csv(csv_path, parse_dates=[0], keep_default_na=False)

# make sure the column exists and is text
messages = df['log_message'].astype(str).tolist()

# 2. embed with a sentence transformer
model = SentenceTransformer('all-MiniLM-L6-v2')  # lightweight & good for semantic similarity
embeddings = model.encode(messages, show_progress_bar=True, convert_to_numpy=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/76 [00:00<?, ?it/s]

In [7]:
embeddings[:2]

array([[-1.02939650e-01,  3.35458964e-02, -2.20260918e-02,
         1.55101146e-03, -9.86918062e-03, -1.78956270e-01,
        -6.34409934e-02, -6.01761565e-02,  2.81109177e-02,
         5.99619336e-02, -1.72617678e-02,  1.43369730e-03,
        -1.49560049e-01,  3.15286336e-03, -5.66030741e-02,
         2.71685310e-02, -1.49890324e-02, -3.54037695e-02,
        -3.62936556e-02, -1.45410830e-02, -5.61489770e-03,
         8.75538513e-02,  4.55120876e-02,  2.50964146e-02,
         1.00187995e-02,  1.24266678e-02, -1.39923573e-01,
         7.68696368e-02,  3.14095467e-02, -4.15248377e-03,
         4.36902568e-02,  1.71250198e-02, -8.00950527e-02,
         5.74005954e-02,  1.89091992e-02,  8.55262130e-02,
         3.96399386e-02, -1.34371832e-01, -1.44358294e-03,
         3.06704384e-03,  1.76854014e-01,  4.44887392e-03,
        -1.69274751e-02,  2.24267188e-02, -4.35049385e-02,
         6.09029364e-03, -9.98165552e-03, -6.23972826e-02,
         1.07372459e-02, -6.04896760e-03, -7.14660957e-02,
        -8.45803693e-03, -3.18019651e-02, -1.00518376e-01,
         2.25858996e-04, -1.89341288e-02, -3.17794606e-02,
         4.00861613e-02,  2.19177660e-02, -2.59528141e-02,
         5.84524609e-02, -8.12509358e-02,  2.12028958e-02,
        -5.02687506e-02,  1.32057257e-02,  1.32676819e-03,
         2.27062758e-02, -3.45794074e-02,  3.91547792e-02,
        -2.09433921e-02,  3.24818562e-03,  4.43960726e-02,
        -9.85357761e-02, -2.88895108e-02, -6.85032550e-03,
         5.38818352e-02,  6.46110103e-02, -2.45059989e-02,
         9.21828672e-02, -7.49869570e-02,  1.23995179e-02,
        -1.00026555e-01, -4.64910604e-02,  6.01570234e-02,
        -2.46480163e-02, -7.08076432e-02, -2.77270433e-02,
         9.72611606e-02,  3.85841057e-02, -1.44292954e-02,
        -7.46869948e-04, -1.04305102e-02, -1.61843225e-02,
         4.43628468e-02,  9.25989356e-03,  7.14166090e-02,
         6.37917668e-02,  4.94930819e-02, -6.02567196e-02,
         4.04806472e-02, -3.42860594e-02, -1.93880908e-02,
         6.61234409e-02,  6.01589121e-02,  1.09371236e-02,
        -5.38629992e-03,  1.44579913e-02,  9.25430581e-02,
        -3.14564034e-02, -1.84351727e-02,  9.91883036e-03,
        -1.85573976e-02,  1.31285354e-03,  2.26976808e-05,
         2.02737353e-03,  2.75256280e-02, -4.81928326e-02,
         5.42825758e-02, -7.32066780e-02,  4.88667265e-02,
         4.98490408e-02, -9.01138876e-03, -4.68905978e-02,
        -4.25886922e-02, -8.19524825e-02,  3.87106761e-02,
         7.85504356e-02,  1.46077096e-32,  1.66706275e-02,
         5.25493622e-02, -1.82448756e-02, -1.26686376e-02,
         6.52836785e-02, -2.11777221e-02, -4.06323001e-02,
         4.14947420e-02, -2.48361379e-02, -1.33068217e-02,
        -5.46753481e-02, -5.99131919e-04, -4.89246566e-03,
        -6.27359822e-02, -3.84878330e-02, -6.13543652e-02,
         8.27405006e-02,  2.34380942e-02, -8.63086153e-03,
         1.31002758e-02,  6.44214675e-02, -4.41362001e-02,
        -6.98633939e-02, -7.36060813e-02, -4.33263928e-02,
         6.96524559e-03, -5.05956411e-02, -1.60911363e-02,
        -5.66794090e-02,  3.35455430e-03,  5.34115210e-02,
         2.47761384e-02, -1.47986710e-02, -2.93242410e-02,
         7.30228499e-02, -1.86833683e-02,  8.13137069e-02,
        -2.69968100e-02, -5.68055920e-02, -6.59388974e-02,
        -5.95398154e-03,  2.85313074e-02, -7.85358325e-02,
        -2.76696729e-03, -3.26472614e-03, -9.28332731e-02,
        -7.27363303e-02, -3.31903175e-02,  1.01411067e-01,
         9.79881287e-02, -9.78740081e-02,  1.98668167e-02,
         2.38837264e-02, -1.81672294e-02, -3.73708718e-02,
         1.96553348e-03,  6.34426102e-02,  1.18271904e-02,
        -1.12041142e-02, -3.87316011e-02,  9.32424143e-02,
         4.26632306e-03, -1.66872889e-02, -6.87464774e-02,
         1.55120036e-02, -4.97755148e-02,  3.34492698e-02,
         8.00032467e-02,  2.12282185e-02,  1.34581894e-01,
        -2.30730195e-02,  5.53858504e-02,  3.07557881e-02,
        -2.93905493e-02,  2.31905077e-02, -9.34307873e-02,
         7.58035257e-02, -5.21200802e-03, -5.14523908e-02,
         3.32689881e-02,  3.67963351e-02, -1.06450040e-02,
         1.01635084e-02, -2.07651500e-02, -5.85518964e-02,
         4.79328819e-02,  2.13695318e-02,  8.76213387e-02,
         3.35488701e-03, -3.80336605e-02, -1.81205515e-02,
         6.87448168e-03,  5.15879504e-02, -4.75598685e-02,
        -6.12064935e-02, -1.45483574e-32,  4.12803376e-03,
         4.59643733e-03, -5.63900694e-02,  4.32466436e-03,
        -1.09444233e-03,  9.31950007e-03, -2.20268592e-02,
         5.79565391e-02, -1.44787645e-02,  4.64155599e-02,
         1.43542901e-01, -6.89757615e-02,  6.09631389e-02,
        -8.93743783e-02,  2.40919311e-02,  2.06011012e-02,
        -2.82415263e-02, -6.48315474e-02,  5.64794838e-02,
        -7.48339808e-03, -3.52058038e-02,  8.51059929e-02,
         1.30359903e-02,  2.02257931e-02, -1.44391116e-02,
        -4.63718399e-02,  1.77210346e-02,  1.59105565e-02,
        -9.51009765e-02, -3.54527123e-02,  2.08696332e-02,
         3.84383695e-03, -8.77918750e-02,  6.44575134e-02,
         1.44170700e-02,  3.84733127e-03,  4.70991433e-02,
         4.94661257e-02,  1.53862555e-02, -2.59578824e-02,
         9.10895020e-02,  1.83307864e-02, -5.89206479e-02,
         2.51993127e-02, -3.30374502e-02,  8.23344663e-02,
         1.74792018e-02,  6.48047403e-02, -1.19674290e-02,
        -3.31778750e-02,  3.00177410e-02,  3.54220122e-02,
        -1.39624374e-02,  6.69272318e-02,  3.87920327e-02,
         6.06916286e-02,  1.17959711e-03, -2.38786526e-02,
        -1.26930460e-01,  1.13845915e-02,  1.59289874e-02,
        -1.29426606e-02, -8.63247961e-02,  8.53661355e-03,
         6.03761263e-02,  1.51122175e-02, -1.19132355e-01,
         1.15234368e-02,  5.97089194e-02, -3.93345840e-02,
         1.55674154e-02,  1.04602342e-02, -4.72457707e-02,
        -2.59243473e-02,  9.98522528e-03,  3.07146721e-02,
        -7.14843869e-02,  6.98968722e-03, -1.55133558e-02,
         2.18863972e-02, -2.78145466e-02,  6.92733154e-02,
        -2.75903363e-02,  2.62429640e-02,  3.52562293e-02,
        -4.26419899e-02,  7.46270060e-04,  6.59867227e-02,
        -5.15104830e-02, -3.58434282e-02, -6.53441437e-03,
        -2.75857896e-02, -1.00125574e-01,  7.83326104e-02,
        -1.45798819e-02, -6.18457321e-08,  2.00324953e-02,
         6.59785047e-02, -2.04702336e-02,  1.64043680e-02,
         7.63001069e-02,  7.32183084e-02,  5.65791503e-03,
        -6.97750715e-04, -3.63798789e-03,  6.02394082e-02,
        -3.27187218e-02, -6.45838231e-02, -5.97953089e-02,
        -1.76695976e-02,  6.10138988e-03, -5.63486526e-03,
        -1.22972272e-01,  6.35818914e-02, -2.19431631e-02,
        -1.16406500e-01,  2.34365985e-02, -7.23525435e-02,
         2.31774189e-02, -6.55987114e-02, -7.42681772e-02,
         2.60146391e-02,  3.59758399e-02,  7.68432841e-02,
        -3.08056958e-02, -2.34794226e-02, -6.30425438e-02,
        -3.62158194e-02, -1.03559801e-02, -4.75602187e-02,
        -2.87522096e-02,  2.96401288e-02, -5.26899658e-03,
         5.67890108e-02, -3.74489813e-03,  3.09612583e-02,
         3.48226950e-02,  3.78607251e-02,  2.10155603e-02,
         2.70691980e-02,  5.25520854e-02,  7.16229454e-02,
        -5.53755695e-03,  4.01094370e-02,  5.16276360e-02,
        -2.67314594e-02,  5.94224446e-02, -4.29224744e-02,
        -1.19760409e-02,  3.05985324e-02, -7.40331635e-02,
         1.84222087e-02, -8.64861719e-03, -8.83557498e-02,
        -5.91984130e-02, -1.00887053e-04,  1.12913638e-01,
         4.57791798e-03, -4.25971672e-02,  3.22623411e-03],
       [ 8.04575440e-03, -3.57392430e-02,  4.93874140e-02,
        -7.19189318e-03,  6.17719721e-04, -9.05685127e-02,
         5.75595126e-02, -4.39445972e-02,  1.74751543e-02,
         5.21202870e-02, -4.62332405e-02,  2.49039400e-02,
         4.80811261e-02,  6.86636344e-02,  3.56146991e-02,
         3.00089102e-02,  2.61449721e-02, -9.05241892e-02,
        -8.02173689e-02,  5.04851267e-02, -7.90870860e-02,
        -1.76854699e-03, -2.48927381e-02,  9.02152658e-02,
         5.83697436e-03, -6.91070706e-02, -6.67965412e-02,
        -6.99111959e-03, -1.04566038e-01, -2.66474299e-02,
         3.05639971e-02,  2.02934220e-02,  2.25454643e-02,
        -4.22682101e-03,  1.11173149e-02,  6.78260848e-02,
         1.06073767e-02,  7.56636038e-02, -8.22777674e-02,
         8.45727604e-03, -6.97612390e-02, -4.21974175e-02,
        -1.05675012e-02,  2.23673470e-02,  5.64496666e-02,
         8.16498976e-03,  1.09344035e-01,  3.16564739e-02,
        -1.76924597e-02, -3.21071334e-02, -3.39975841e-02,
        -4.91875340e-04,  3.72882513e-03,  2.83771735e-02,
        -1.28521789e-02, -1.07930670e-03, -6.32418916e-02,
         6.89900294e-02,  1.77270453e-02, -5.20959422e-02,
         8.28308705e-03,  5.45032397e-02, -5.42099811e-02,
        -4.53332923e-02, -4.07494605e-02, -2.82698739e-02,
         1.23606399e-02, -2.13816036e-02, -2.36265827e-02,
         1.25317778e-02, -2.37170793e-02,  3.97411324e-02,
        -1.24362282e-01,  7.60625675e-02,  5.50833642e-02,
         8.28216821e-02,  2.97119133e-02, -1.84067264e-02,
        -1.96194686e-02,  5.54319769e-02, -3.49144302e-02,
        -4.14677598e-02, -3.37047465e-02,  7.31324106e-02,
         4.41836603e-02,  2.55247261e-02, -8.26403126e-03,
        -1.07322969e-02, -4.26243730e-02, -2.84961425e-03,
         7.38559216e-02,  2.27767974e-02,  7.15398695e-04,
         4.36012372e-02,  5.09079695e-02,  6.38482869e-02,
        -2.73155514e-02, -6.55021667e-02, -7.69265220e-02,
         3.55172269e-02,  9.60494503e-02,  2.18196008e-02,
         1.20154526e-02, -1.17863882e-02, -4.57928050e-03,
        -8.58034380e-03,  3.37150171e-02,  2.31917929e-02,
        -7.58325532e-02, -5.23879044e-02,  4.53934334e-02,
        -3.80785912e-02, -3.34905200e-02,  9.20353010e-02,
         2.87688691e-02, -3.33817638e-02, -1.95852900e-03,
        -3.04517394e-04, -1.70498751e-02,  2.85335667e-02,
        -8.81096646e-02, -4.02253009e-02, -4.00093421e-02,
        -1.03193345e-02, -2.51968671e-02,  2.14092974e-02,
         1.31045282e-01, -5.29632525e-34, -1.09651707e-01,
         1.29811764e-02,  5.92657924e-03,  4.73506153e-02,
        -8.60297680e-03, -3.67088877e-02,  3.05214673e-02,
         5.53067140e-02, -4.71985415e-02, -1.25119248e-02,
        -1.15366429e-01,  9.08002444e-03,  1.07346535e-01,
        -4.94734570e-02, -1.34290708e-02, -4.61562239e-02,
         2.45320890e-02,  9.45080165e-03,  2.04324219e-02,
        -3.99918705e-02, -4.67826091e-02,  2.21171416e-02,
        -4.58187014e-02, -8.13268684e-03, -7.65671069e-03,
         1.92284863e-02,  4.85845357e-02, -2.55902633e-02,
         1.61543814e-03, -1.37180295e-02,  9.67304874e-03,
         7.36414129e-03,  1.14088720e-02,  1.28853470e-01,
         7.71838054e-03,  7.06362501e-02,  2.54452117e-02,
         4.06524017e-02,  2.44039577e-02,  1.43776704e-02,
        -6.00932762e-02,  7.38180578e-02, -2.44700760e-02,
         8.98901597e-02,  3.17047932e-03,  1.01834491e-01,
         4.17741947e-02, -5.95177300e-02, -3.23181823e-02,
         3.80938016e-02,  1.21155400e-02, -4.07834351e-02,
         2.84823142e-02,  4.90988456e-02, -9.35706310e-03,
         6.50074109e-02,  7.23532364e-02, -1.67793538e-02,
        -8.22415575e-03, -1.61572788e-02,  5.96225448e-02,
        -3.36083621e-02,  2.12108418e-02, -6.06090687e-02,
         1.54377639e-01, -7.24146441e-02, -3.77272479e-02,
        -3.26889902e-02, -1.80381839e-03, -1.01960311e-02,
        -1.60679489e-03, -6.91846907e-02,  8.28444511e-02,
         9.88840237e-02,  3.45467962e-03, -9.90247652e-02,
        -3.52827162e-02, -7.13178739e-02, -4.96000350e-02,
        -3.43954712e-02, -8.13041776e-02,  4.81447838e-02,
         5.00682741e-03, -2.21499614e-02, -5.60056530e-02,
         1.00067472e-02, -3.59794162e-02,  1.06184348e-01,
        -4.54196557e-02,  7.16393590e-02, -2.36773137e-02,
         9.98142269e-03,  2.73602027e-02,  1.05985500e-01,
         4.60164286e-02,  9.59027709e-34, -1.12306952e-01,
         2.78912131e-02, -3.35901305e-02,  5.39242141e-02,
        -2.22291294e-02,  1.53769320e-02,  3.10411695e-02,
         3.39011103e-02,  7.43167028e-02,  3.42471227e-02,
        -3.35058291e-03, -2.05350667e-02, -3.62370275e-02,
         2.29334645e-02, -3.01992409e-02, -1.00819923e-01,
         3.29194181e-02,  6.77542910e-02,  1.35645028e-02,
        -5.20550227e-03, -6.58158585e-02,  9.54550281e-02,
        -1.34038860e-02,  1.53885633e-02, -7.22936168e-02,
         9.67836007e-02, -8.08119774e-02, -4.53453558e-03,
        -6.42011464e-02, -4.99278307e-02,  4.64197844e-02,
         2.21341103e-02,  3.13109010e-02,  9.13569108e-02,
        -4.61120084e-02, -1.02761142e-01,  3.04415897e-02,
         5.09875566e-02,  6.70141205e-02,  1.04043055e-02,
         1.63533352e-02,  3.92031372e-02,  2.17154231e-02,
         5.36603667e-02,  3.62809710e-02, -4.22140025e-02,
        -2.47227345e-02,  1.90311577e-02,  3.61724272e-02,
         6.37021065e-02, -3.21583427e-03, -8.50387476e-03,
         3.94655578e-02,  9.02653579e-03,  1.93095915e-02,
         6.60717711e-02,  1.02694305e-02, -4.43853959e-02,
        -1.56523529e-02, -1.55714350e-02,  1.32903764e-02,
        -1.16108470e-02,  4.21832353e-02, -5.44776805e-02,
         1.29237205e-01, -2.25756709e-02,  5.26204295e-02,
        -1.58437230e-02,  9.33165103e-02,  6.38024183e-03,
        -9.36162286e-03, -6.08875938e-02, -3.27308215e-02,
        -3.44817340e-02,  3.29973921e-02, -4.79391403e-02,
        -9.81301293e-02,  2.91165095e-02, -2.70903353e-02,
         1.81867201e-02, -1.73859708e-02, -4.40371521e-02,
        -7.97002539e-02,  3.01647149e-02, -6.35260791e-02,
         1.25962878e-02,  8.50250348e-02, -4.58910838e-02,
         5.81017807e-02, -2.71001868e-02,  8.42776150e-02,
        -4.09972556e-02, -3.37656029e-02,  1.02087939e-02,
        -2.54193097e-02, -1.40610323e-08,  4.94447015e-02,
        -9.04356763e-02, -6.06710128e-02,  8.29530060e-02,
        -3.29033025e-02,  4.14910540e-02,  9.99595225e-03,
         6.96136896e-03,  3.99233401e-03, -3.24333236e-02,
        -3.14657576e-02, -5.33161685e-02, -3.80913056e-02,
         1.62077323e-02,  2.45778579e-02, -7.26419166e-02,
        -6.56893328e-02, -8.23131502e-02, -8.00500810e-02,
        -5.36649153e-02,  5.60894497e-02, -1.10913105e-02,
         9.62172518e-04, -1.22690298e-01, -5.13836630e-02,
         9.96702444e-03,  1.00696040e-02,  1.07073084e-01,
         1.19758137e-02,  1.00423964e-02, -6.28261715e-02,
        -7.49697462e-02, -6.34078030e-03, -2.72201505e-02,
        -1.28096223e-01, -2.62459982e-02, -1.81464367e-02,
        -9.85360518e-02, -3.02990191e-02, -4.02614996e-02,
         9.94290411e-02,  5.35999462e-02,  2.74899509e-02,
        -5.53684030e-03,  8.43571052e-02,  8.35161880e-02,
         3.74304391e-02,  7.11937100e-02,  2.98903044e-02,
         2.32728515e-02, -3.62112150e-02,  6.20539635e-02,
         2.15148292e-02,  5.19732796e-02,  1.45337600e-02,
        -4.60966416e-02,  5.02554141e-02, -7.27027804e-02,
         2.92778909e-02,  5.62662780e-02, -3.86355110e-02,
         1.53831635e-02, -6.23094849e-02, -2.77466141e-02]], dtype=float32)

In [8]:
# 3. cluster with DBSCAN
# epsilon and min_samples will need tuning depending on dataset/closeness of messages.
# metric='cosine' works well for transformer vectors.
clustering = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
labels = clustering.fit_predict(embeddings)

# 4. attach labels back to data frame
df['cluster'] = labels

# inspect some clusters
# for cluster_id in sorted(df['cluster'].unique()):
#     print(f"Cluster {cluster_id} (n={len(df[df['cluster'] == cluster_id])}):")
#     for msg in df[df['cluster'] == cluster_id]['log_message'].head(5):
#         print("    ", msg)
#     print()

In [9]:
df['cluster'].head(5)

0    0
1    1
2    2
3    0
4    0
Name: cluster, dtype: int64

In [10]:
# count records per cluster, keep only those with more than 10 entries
cluster_counts = df['cluster'].value_counts()
big_clusters = cluster_counts[cluster_counts > 10].sort_values(ascending=False)

for cid, cnt in big_clusters.items():
    print(f"Cluster {cid} (n={cnt}):")
    # show 5 messages from this cluster
    msgs = df.loc[df['cluster'] == cid, 'log_message'].head(5)
    for m in msgs:
        print("   ", m)
    print()

Cluster 0 (n=1017):
    nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
    nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
    nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
    nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
    nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 5 (n=147):
    nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
    nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
    nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
    nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
    nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

Cluster 11 (n=100):
    User User685 logged out.
    User User395 logged in.
    User User225 logged in.
    User User494 logged out.
    User User900 logged in.

Cluster 13 (n=86):
    Backup started at 2025-05-14 07:06:55.
    Backup started at 2025-02-15 20:00:19.
    Backup ended at 2025-08-08 13:06:23.
    Backup started at 2025-11-14 08:27:43.
    Backup started at 2025-12-09 10:19:11.

Cluster 7 (n=60):
    Multiple bad login attempts detected on user 8538 account
    Multiple login failures occurred on user 9052 account
    User 7153 made multiple incorrect login attempts
    User 8300 made multiple incorrect login attempts
    Multiple login failures were detected for user 6373

Cluster 8 (n=60):
    Backup completed successfully.
    Backup completed successfully.
    Backup completed successfully.
    Backup completed successfully.
    Backup completed successfully.

Cluster 21 (n=58):
    System updated to version 3.9.1.
    System updated to version 5.5.4.
    System updated to version 4.7.4.
    System updated to version 3.7.7.
    System updated to version 2.6.2.

Cluster 3 (n=57):
    Shard 6 replication task ended in failure
    Data replication task for shard 14 did not complete
    Data replication task failed for shard 17
    Replication of data to shard 14 failed
    Data replication task for shard 6 did not complete

Cluster 4 (n=53):
    File data_6169.csv uploaded successfully by user User953.
    File data_3847.csv uploaded successfully by user User175.
    File data_7366.csv uploaded successfully by user User282.
    File data_1206.csv uploaded successfully by user User359.
    File data_1503.csv uploaded successfully by user User151.

Cluster 17 (n=52):
    Denied access attempt on restricted account Account2682
    Unauthorized login attempt on protected account Account5030
    Account Account9437 blocked due to failed login
    Account Account7999 access denied due to login failure
    Invalid login attempt made on secured account Account7864

Cluster 6 (n=51):
    Critical system unit error: unit ID Component55
    System component malfunction: component ID Component79
    Critical system element is down: element ID Component96
    Essential system part malfunction: part ID Component6
    Failure occurred in critical system component: component ID Component92

Cluster 32 (n=51):
    Disk cleanup completed successfully.
    Disk cleanup completed successfully.
    Disk cleanup completed successfully.
    Disk cleanup completed successfully.
    Disk cleanup completed successfully.

Cluster 16 (n=48):
    System reboot initiated by user User243.
    System reboot initiated by user User471.
    System reboot initiated by user User216.
    System reboot initiated by user User639.
    System reboot initiated by user User819.

Cluster 20 (n=48):
    User 7662 tried to bypass API security measures
    User 2367 failed to provide valid API access credentials
    User 3569 made an unauthorized API request
    Unauthorized user 2968 tried to access restricted API
    User 2186 attempted to access API without proper authorization

Cluster 9 (n=44):
    Account with ID 5351 created by User634.
    Account with ID 7813 created by User373.
    Account with ID 9827 created by User965.
    Account with ID 2520 created by User546.
    Account with ID 2300 created by User964.

Cluster 1 (n=39):
    Email service experiencing issues with sending
    Email server encountered a sending fault
    Mail service encountered a delivery glitch
    Service disruption caused by email sending error
    Email system had a problem sending emails

Cluster 10 (n=30):
    nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
    nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
    nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
    nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
    nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 34 (n=25):
    Abnormal behavior found on server 10, possible security threat
    Security alert: suspicious activity on server 1
    Anomalous activity identified on server 23, security review recommended
    Server 27 experienced potential security incident, review required
    Server 36 experienced potential security incident, review required

Cluster 14 (n=20):
    Detection of multiple disk faults in RAID setup
    RAID array suffered multiple hard drive failures
    RAID array experienced multiple disk crashes
    Multiple hard drive issues in RAID configuration found
    Identification of multiple faulty disks in RAID array

Cluster 52 (n=20):
    Service health check was not successful because of SSL certificate validation failures.
    Invalid SSL certificate resulted in a failed service health check.
    Service health check failure was due to an invalid or improperly configured SSL certificate.
    An issue with the SSL certificate caused the service health check to fail.
    Service health check failure was caused by an expired SSL certificate.

Cluster 53 (n=20):
    Module X experienced an invalid data format issue
    Input format mismatch occurred in module X
    Module X reported an error in input format validation
    Module X failed to process input due to formatting error
    Input data format in module X was invalid or corrupted

Cluster 18 (n=17):
    Boot process terminated unexpectedly due to kernel issue
    System encountered kernel panic during initialization phase
    Boot process was stopped by kernel malfunction
    System encountered kernel failure during bootup sequence
    Boot sequence failed due to kernel panic

Cluster 25 (n=13):
    System configuration is no longer valid
    Configuration is corrupted throughout the system
    Cross-system configuration failure occurred
    System configuration is experiencing errors
    Configuration malfunction is system-wide

Cluster 42 (n=13):
    User 5127 has escalated admin privileges without authorization
    User 9745 has escalated to admin level
    User 8483 escalated privileges to admin level
    User 1987 has escalated to admin level
    User 8395 escalated privileges to admin level

Cluster 59 (n=12):
    Potential security threat: Admin privilege escalation for user 5130
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
    Potential security threat: Admin privilege escalation for user 1554
    Warning: Potential admin privilege escalation for user 5720

Cluster 26 (n=11):
    Privilege elevation detected for user 5038
    Elevation of admin privileges detected for user 6137
    Elevation of admin privileges detected for user 4907
    User 6069 has been granted elevated admin privileges
    Admin privilege elevation warning for user 7574

In [11]:
import re

def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (out|in).": "User Action",
        r"Backup (started|ended) at.*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version  .*" : "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"system reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.match(pattern, log_message, flags=re.IGNORECASE):
            return label
    return None

In [12]:
classify_with_regex("User User123 Logged Out.")

'User Action'

In [13]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df[df.regex_label.notnull()]

,timestamp,source,log_message,target_label,cluster,regex_label
7,10-11-2025 08:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,4,System Notification
14,01-04-2025 01:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,4,System Notification
15,05-01-2025 09:41,ModernCRM,Backup completed successfully.,System Notification,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,11,User Action
...,...,...,...,...,...,...
2368,12/13/2025 20:04,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,32,System Notification
2381,09-05-2025 06:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,32,System Notification
2394,04-03-2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,32,System Notification
2395,05-02-2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,13,System Notification
2403,10-01-2025 01:31,ModernCRM,Backup completed successfully.,System Notification,8,System Notification

In [14]:
df.shape

(2410, 6)

In [15]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1968, 6)

In [16]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <= 5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [17]:
df_non_legacy = df_non_regex[df_non_regex.source != 'LegacyCRM']
df_non_legacy.source.unique()

<StringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [18]:
filtered_messages = df_non_legacy['log_message'].astype(str).tolist()

model = SentenceTransformer('all-MiniLM-L6-v2')  # lightweight & good for semantic similarity
filtered_embeddings = model.encode(filtered_messages, show_progress_bar=True, convert_to_numpy=True)
filtered_embeddings[:2]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/62 [00:00<?, ?it/s]

array([[-1.02939650e-01,  3.35458964e-02, -2.20260918e-02,
         1.55101146e-03, -9.86918062e-03, -1.78956270e-01,
        -6.34409934e-02, -6.01761565e-02,  2.81109177e-02,
         5.99619336e-02, -1.72617678e-02,  1.43369730e-03,
        -1.49560049e-01,  3.15286336e-03, -5.66030741e-02,
         2.71685310e-02, -1.49890324e-02, -3.54037695e-02,
        -3.62936556e-02, -1.45410830e-02, -5.61489770e-03,
         8.75538513e-02,  4.55120876e-02,  2.50964146e-02,
         1.00187995e-02,  1.24266678e-02, -1.39923573e-01,
         7.68696368e-02,  3.14095467e-02, -4.15248377e-03,
         4.36902568e-02,  1.71250198e-02, -8.00950527e-02,
         5.74005954e-02,  1.89091992e-02,  8.55262130e-02,
         3.96399386e-02, -1.34371832e-01, -1.44358294e-03,
         3.06704384e-03,  1.76854014e-01,  4.44887392e-03,
        -1.69274751e-02,  2.24267188e-02, -4.35049385e-02,
         6.09029364e-03, -9.98165552e-03, -6.23972826e-02,
         1.07372459e-02, -6.04896760e-03, -7.14660957e-02,
        -8.45803693e-03, -3.18019651e-02, -1.00518376e-01,
         2.25858996e-04, -1.89341288e-02, -3.17794606e-02,
         4.00861613e-02,  2.19177660e-02, -2.59528141e-02,
         5.84524609e-02, -8.12509358e-02,  2.12028958e-02,
        -5.02687506e-02,  1.32057257e-02,  1.32676819e-03,
         2.27062758e-02, -3.45794074e-02,  3.91547792e-02,
        -2.09433921e-02,  3.24818562e-03,  4.43960726e-02,
        -9.85357761e-02, -2.88895108e-02, -6.85032550e-03,
         5.38818352e-02,  6.46110103e-02, -2.45059989e-02,
         9.21828672e-02, -7.49869570e-02,  1.23995179e-02,
        -1.00026555e-01, -4.64910604e-02,  6.01570234e-02,
        -2.46480163e-02, -7.08076432e-02, -2.77270433e-02,
         9.72611606e-02,  3.85841057e-02, -1.44292954e-02,
        -7.46869948e-04, -1.04305102e-02, -1.61843225e-02,
         4.43628468e-02,  9.25989356e-03,  7.14166090e-02,
         6.37917668e-02,  4.94930819e-02, -6.02567196e-02,
         4.04806472e-02, -3.42860594e-02, -1.93880908e-02,
         6.61234409e-02,  6.01589121e-02,  1.09371236e-02,
        -5.38629992e-03,  1.44579913e-02,  9.25430581e-02,
        -3.14564034e-02, -1.84351727e-02,  9.91883036e-03,
        -1.85573976e-02,  1.31285354e-03,  2.26976808e-05,
         2.02737353e-03,  2.75256280e-02, -4.81928326e-02,
         5.42825758e-02, -7.32066780e-02,  4.88667265e-02,
         4.98490408e-02, -9.01138876e-03, -4.68905978e-02,
        -4.25886922e-02, -8.19524825e-02,  3.87106761e-02,
         7.85504356e-02,  1.46077096e-32,  1.66706275e-02,
         5.25493622e-02, -1.82448756e-02, -1.26686376e-02,
         6.52836785e-02, -2.11777221e-02, -4.06323001e-02,
         4.14947420e-02, -2.48361379e-02, -1.33068217e-02,
        -5.46753481e-02, -5.99131919e-04, -4.89246566e-03,
        -6.27359822e-02, -3.84878330e-02, -6.13543652e-02,
         8.27405006e-02,  2.34380942e-02, -8.63086153e-03,
         1.31002758e-02,  6.44214675e-02, -4.41362001e-02,
        -6.98633939e-02, -7.36060813e-02, -4.33263928e-02,
         6.96524559e-03, -5.05956411e-02, -1.60911363e-02,
        -5.66794090e-02,  3.35455430e-03,  5.34115210e-02,
         2.47761384e-02, -1.47986710e-02, -2.93242410e-02,
         7.30228499e-02, -1.86833683e-02,  8.13137069e-02,
        -2.69968100e-02, -5.68055920e-02, -6.59388974e-02,
        -5.95398154e-03,  2.85313074e-02, -7.85358325e-02,
        -2.76696729e-03, -3.26472614e-03, -9.28332731e-02,
        -7.27363303e-02, -3.31903175e-02,  1.01411067e-01,
         9.79881287e-02, -9.78740081e-02,  1.98668167e-02,
         2.38837264e-02, -1.81672294e-02, -3.73708718e-02,
         1.96553348e-03,  6.34426102e-02,  1.18271904e-02,
        -1.12041142e-02, -3.87316011e-02,  9.32424143e-02,
         4.26632306e-03, -1.66872889e-02, -6.87464774e-02,
         1.55120036e-02, -4.97755148e-02,  3.34492698e-02,
         8.00032467e-02,  2.12282185e-02,  1.34581894e-01,
        -2.30730195e-02,  5.53858504e-02,  3.07557881e-02,
        -2.93905493e-02,  2.31905077e-02, -9.34307873e-02,
         7.58035257e-02, -5.21200802e-03, -5.14523908e-02,
         3.32689881e-02,  3.67963351e-02, -1.06450040e-02,
         1.01635084e-02, -2.07651500e-02, -5.85518964e-02,
         4.79328819e-02,  2.13695318e-02,  8.76213387e-02,
         3.35488701e-03, -3.80336605e-02, -1.81205515e-02,
         6.87448168e-03,  5.15879504e-02, -4.75598685e-02,
        -6.12064935e-02, -1.45483574e-32,  4.12803376e-03,
         4.59643733e-03, -5.63900694e-02,  4.32466436e-03,
        -1.09444233e-03,  9.31950007e-03, -2.20268592e-02,
         5.79565391e-02, -1.44787645e-02,  4.64155599e-02,
         1.43542901e-01, -6.89757615e-02,  6.09631389e-02,
        -8.93743783e-02,  2.40919311e-02,  2.06011012e-02,
        -2.82415263e-02, -6.48315474e-02,  5.64794838e-02,
        -7.48339808e-03, -3.52058038e-02,  8.51059929e-02,
         1.30359903e-02,  2.02257931e-02, -1.44391116e-02,
        -4.63718399e-02,  1.77210346e-02,  1.59105565e-02,
        -9.51009765e-02, -3.54527123e-02,  2.08696332e-02,
         3.84383695e-03, -8.77918750e-02,  6.44575134e-02,
         1.44170700e-02,  3.84733127e-03,  4.70991433e-02,
         4.94661257e-02,  1.53862555e-02, -2.59578824e-02,
         9.10895020e-02,  1.83307864e-02, -5.89206479e-02,
         2.51993127e-02, -3.30374502e-02,  8.23344663e-02,
         1.74792018e-02,  6.48047403e-02, -1.19674290e-02,
        -3.31778750e-02,  3.00177410e-02,  3.54220122e-02,
        -1.39624374e-02,  6.69272318e-02,  3.87920327e-02,
         6.06916286e-02,  1.17959711e-03, -2.38786526e-02,
        -1.26930460e-01,  1.13845915e-02,  1.59289874e-02,
        -1.29426606e-02, -8.63247961e-02,  8.53661355e-03,
         6.03761263e-02,  1.51122175e-02, -1.19132355e-01,
         1.15234368e-02,  5.97089194e-02, -3.93345840e-02,
         1.55674154e-02,  1.04602342e-02, -4.72457707e-02,
        -2.59243473e-02,  9.98522528e-03,  3.07146721e-02,
        -7.14843869e-02,  6.98968722e-03, -1.55133558e-02,
         2.18863972e-02, -2.78145466e-02,  6.92733154e-02,
        -2.75903363e-02,  2.62429640e-02,  3.52562293e-02,
        -4.26419899e-02,  7.46270060e-04,  6.59867227e-02,
        -5.15104830e-02, -3.58434282e-02, -6.53441437e-03,
        -2.75857896e-02, -1.00125574e-01,  7.83326104e-02,
        -1.45798819e-02, -6.18457321e-08,  2.00324953e-02,
         6.59785047e-02, -2.04702336e-02,  1.64043680e-02,
         7.63001069e-02,  7.32183084e-02,  5.65791503e-03,
        -6.97750715e-04, -3.63798789e-03,  6.02394082e-02,
        -3.27187218e-02, -6.45838231e-02, -5.97953089e-02,
        -1.76695976e-02,  6.10138988e-03, -5.63486526e-03,
        -1.22972272e-01,  6.35818914e-02, -2.19431631e-02,
        -1.16406500e-01,  2.34365985e-02, -7.23525435e-02,
         2.31774189e-02, -6.55987114e-02, -7.42681772e-02,
         2.60146391e-02,  3.59758399e-02,  7.68432841e-02,
        -3.08056958e-02, -2.34794226e-02, -6.30425438e-02,
        -3.62158194e-02, -1.03559801e-02, -4.75602187e-02,
        -2.87522096e-02,  2.96401288e-02, -5.26899658e-03,
         5.67890108e-02, -3.74489813e-03,  3.09612583e-02,
         3.48226950e-02,  3.78607251e-02,  2.10155603e-02,
         2.70691980e-02,  5.25520854e-02,  7.16229454e-02,
        -5.53755695e-03,  4.01094370e-02,  5.16276360e-02,
        -2.67314594e-02,  5.94224446e-02, -4.29224744e-02,
        -1.19760409e-02,  3.05985324e-02, -7.40331635e-02,
         1.84222087e-02, -8.64861719e-03, -8.83557498e-02,
        -5.91984130e-02, -1.00887053e-04,  1.12913638e-01,
         4.57791798e-03, -4.25971672e-02,  3.22623411e-03],
       [ 8.04575440e-03, -3.57392430e-02,  4.93874140e-02,
        -7.19189318e-03,  6.17719721e-04, -9.05685127e-02,
         5.75595126e-02, -4.39445972e-02,  1.74751543e-02,
         5.21202870e-02, -4.62332405e-02,  2.49039400e-02,
         4.80811261e-02,  6.86636344e-02,  3.56146991e-02,
         3.00089102e-02,  2.61449721e-02, -9.05241892e-02,
        -8.02173689e-02,  5.04851267e-02, -7.90870860e-02,
        -1.76854699e-03, -2.48927381e-02,  9.02152658e-02,
         5.83697436e-03, -6.91070706e-02, -6.67965412e-02,
        -6.99111959e-03, -1.04566038e-01, -2.66474299e-02,
         3.05639971e-02,  2.02934220e-02,  2.25454643e-02,
        -4.22682101e-03,  1.11173149e-02,  6.78260848e-02,
         1.06073767e-02,  7.56636038e-02, -8.22777674e-02,
         8.45727604e-03, -6.97612390e-02, -4.21974175e-02,
        -1.05675012e-02,  2.23673470e-02,  5.64496666e-02,
         8.16498976e-03,  1.09344035e-01,  3.16564739e-02,
        -1.76924597e-02, -3.21071334e-02, -3.39975841e-02,
        -4.91875340e-04,  3.72882513e-03,  2.83771735e-02,
        -1.28521789e-02, -1.07930670e-03, -6.32418916e-02,
         6.89900294e-02,  1.77270453e-02, -5.20959422e-02,
         8.28308705e-03,  5.45032397e-02, -5.42099811e-02,
        -4.53332923e-02, -4.07494605e-02, -2.82698739e-02,
         1.23606399e-02, -2.13816036e-02, -2.36265827e-02,
         1.25317778e-02, -2.37170793e-02,  3.97411324e-02,
        -1.24362282e-01,  7.60625675e-02,  5.50833642e-02,
         8.28216821e-02,  2.97119133e-02, -1.84067264e-02,
        -1.96194686e-02,  5.54319769e-02, -3.49144302e-02,
        -4.14677598e-02, -3.37047465e-02,  7.31324106e-02,
         4.41836603e-02,  2.55247261e-02, -8.26403126e-03,
        -1.07322969e-02, -4.26243730e-02, -2.84961425e-03,
         7.38559216e-02,  2.27767974e-02,  7.15398695e-04,
         4.36012372e-02,  5.09079695e-02,  6.38482869e-02,
        -2.73155514e-02, -6.55021667e-02, -7.69265220e-02,
         3.55172269e-02,  9.60494503e-02,  2.18196008e-02,
         1.20154526e-02, -1.17863882e-02, -4.57928050e-03,
        -8.58034380e-03,  3.37150171e-02,  2.31917929e-02,
        -7.58325532e-02, -5.23879044e-02,  4.53934334e-02,
        -3.80785912e-02, -3.34905200e-02,  9.20353010e-02,
         2.87688691e-02, -3.33817638e-02, -1.95852900e-03,
        -3.04517394e-04, -1.70498751e-02,  2.85335667e-02,
        -8.81096646e-02, -4.02253009e-02, -4.00093421e-02,
        -1.03193345e-02, -2.51968671e-02,  2.14092974e-02,
         1.31045282e-01, -5.29632525e-34, -1.09651707e-01,
         1.29811764e-02,  5.92657924e-03,  4.73506153e-02,
        -8.60297680e-03, -3.67088877e-02,  3.05214673e-02,
         5.53067140e-02, -4.71985415e-02, -1.25119248e-02,
        -1.15366429e-01,  9.08002444e-03,  1.07346535e-01,
        -4.94734570e-02, -1.34290708e-02, -4.61562239e-02,
         2.45320890e-02,  9.45080165e-03,  2.04324219e-02,
        -3.99918705e-02, -4.67826091e-02,  2.21171416e-02,
        -4.58187014e-02, -8.13268684e-03, -7.65671069e-03,
         1.92284863e-02,  4.85845357e-02, -2.55902633e-02,
         1.61543814e-03, -1.37180295e-02,  9.67304874e-03,
         7.36414129e-03,  1.14088720e-02,  1.28853470e-01,
         7.71838054e-03,  7.06362501e-02,  2.54452117e-02,
         4.06524017e-02,  2.44039577e-02,  1.43776704e-02,
        -6.00932762e-02,  7.38180578e-02, -2.44700760e-02,
         8.98901597e-02,  3.17047932e-03,  1.01834491e-01,
         4.17741947e-02, -5.95177300e-02, -3.23181823e-02,
         3.80938016e-02,  1.21155400e-02, -4.07834351e-02,
         2.84823142e-02,  4.90988456e-02, -9.35706310e-03,
         6.50074109e-02,  7.23532364e-02, -1.67793538e-02,
        -8.22415575e-03, -1.61572788e-02,  5.96225448e-02,
        -3.36083621e-02,  2.12108418e-02, -6.06090687e-02,
         1.54377639e-01, -7.24146441e-02, -3.77272479e-02,
        -3.26889902e-02, -1.80381839e-03, -1.01960311e-02,
        -1.60679489e-03, -6.91846907e-02,  8.28444511e-02,
         9.88840237e-02,  3.45467962e-03, -9.90247652e-02,
        -3.52827162e-02, -7.13178739e-02, -4.96000350e-02,
        -3.43954712e-02, -8.13041776e-02,  4.81447838e-02,
         5.00682741e-03, -2.21499614e-02, -5.60056530e-02,
         1.00067472e-02, -3.59794162e-02,  1.06184348e-01,
        -4.54196557e-02,  7.16393590e-02, -2.36773137e-02,
         9.98142269e-03,  2.73602027e-02,  1.05985500e-01,
         4.60164286e-02,  9.59027709e-34, -1.12306952e-01,
         2.78912131e-02, -3.35901305e-02,  5.39242141e-02,
        -2.22291294e-02,  1.53769320e-02,  3.10411695e-02,
         3.39011103e-02,  7.43167028e-02,  3.42471227e-02,
        -3.35058291e-03, -2.05350667e-02, -3.62370275e-02,
         2.29334645e-02, -3.01992409e-02, -1.00819923e-01,
         3.29194181e-02,  6.77542910e-02,  1.35645028e-02,
        -5.20550227e-03, -6.58158585e-02,  9.54550281e-02,
        -1.34038860e-02,  1.53885633e-02, -7.22936168e-02,
         9.67836007e-02, -8.08119774e-02, -4.53453558e-03,
        -6.42011464e-02, -4.99278307e-02,  4.64197844e-02,
         2.21341103e-02,  3.13109010e-02,  9.13569108e-02,
        -4.61120084e-02, -1.02761142e-01,  3.04415897e-02,
         5.09875566e-02,  6.70141205e-02,  1.04043055e-02,
         1.63533352e-02,  3.92031372e-02,  2.17154231e-02,
         5.36603667e-02,  3.62809710e-02, -4.22140025e-02,
        -2.47227345e-02,  1.90311577e-02,  3.61724272e-02,
         6.37021065e-02, -3.21583427e-03, -8.50387476e-03,
         3.94655578e-02,  9.02653579e-03,  1.93095915e-02,
         6.60717711e-02,  1.02694305e-02, -4.43853959e-02,
        -1.56523529e-02, -1.55714350e-02,  1.32903764e-02,
        -1.16108470e-02,  4.21832353e-02, -5.44776805e-02,
         1.29237205e-01, -2.25756709e-02,  5.26204295e-02,
        -1.58437230e-02,  9.33165103e-02,  6.38024183e-03,
        -9.36162286e-03, -6.08875938e-02, -3.27308215e-02,
        -3.44817340e-02,  3.29973921e-02, -4.79391403e-02,
        -9.81301293e-02,  2.91165095e-02, -2.70903353e-02,
         1.81867201e-02, -1.73859708e-02, -4.40371521e-02,
        -7.97002539e-02,  3.01647149e-02, -6.35260791e-02,
         1.25962878e-02,  8.50250348e-02, -4.58910838e-02,
         5.81017807e-02, -2.71001868e-02,  8.42776150e-02,
        -4.09972556e-02, -3.37656029e-02,  1.02087939e-02,
        -2.54193097e-02, -1.40610323e-08,  4.94447015e-02,
        -9.04356763e-02, -6.06710128e-02,  8.29530060e-02,
        -3.29033025e-02,  4.14910540e-02,  9.99595225e-03,
         6.96136896e-03,  3.99233401e-03, -3.24333236e-02,
        -3.14657576e-02, -5.33161685e-02, -3.80913056e-02,
         1.62077323e-02,  2.45778579e-02, -7.26419166e-02,
        -6.56893328e-02, -8.23131502e-02, -8.00500810e-02,
        -5.36649153e-02,  5.60894497e-02, -1.10913105e-02,
         9.62172518e-04, -1.22690298e-01, -5.13836630e-02,
         9.96702444e-03,  1.00696040e-02,  1.07073084e-01,
         1.19758137e-02,  1.00423964e-02, -6.28261715e-02,
        -7.49697462e-02, -6.34078030e-03, -2.72201505e-02,
        -1.28096223e-01, -2.62459982e-02, -1.81464367e-02,
        -9.85360518e-02, -3.02990191e-02, -4.02614996e-02,
         9.94290411e-02,  5.35999462e-02,  2.74899509e-02,
        -5.53684030e-03,  8.43571052e-02,  8.35161880e-02,
         3.74304391e-02,  7.11937100e-02,  2.98903044e-02,
         2.32728515e-02, -3.62112150e-02,  6.20539635e-02,
         2.15148292e-02,  5.19732796e-02,  1.45337600e-02,
        -4.60966416e-02,  5.02554141e-02, -7.27027804e-02,
         2.92778909e-02,  5.62662780e-02, -3.86355110e-02,
         1.53831635e-02, -6.23094849e-02, -2.77466141e-02]], dtype=float32)

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Get target labels for filtered data
y_filtered = df_non_legacy['target_label'].values

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    filtered_embeddings, y_filtered, test_size=0.2, random_state=42
)

# Train logistic regression model
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)

# Evaluate
train_score = lr_model.score(X_train, y_train)
test_score = lr_model.score(X_test, y_test)

print(f"Train accuracy: {train_score:.4f}")
print(f"Test accuracy: {test_score:.4f}")

Train accuracy: 0.9955
Test accuracy: 0.9924

In [20]:
import joblib

joblib.dump(lr_model, '../models/log_classifier.joblib')

['../models/log_classifier.joblib']